version: "3.8" # this the version of Docker Compose
services:
  app:
    build:
      context: ./ 
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - SEARCH_API_URL: ${SEARCH_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules