export interface IEtablissement {
    type_etablissement: string | null
    situation: string | null
    rid: string | null
    designation: string | null
    enseigne: string | null
    ape: string | null
    code_ape: string | null
    activites_secondaires: string | null
    code_nafa: string | null
    code_nafa_secondaires: string | null
    adresse_physique: string | null
    code_postal_physique: string | null
    ville_physique: string | null
    adresse_postale: string | null
    code_postal_postale: string | null
    ville_postale: string | null
    date_creation: string | null
    date_debut_activite: string | null
    date_fin_activite: string | null
    convention_collective: string | null
}